# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: circleci/node:14.17.3-browsers

clone:
  depth: full

pipelines:
  pull-requests:  
    '**':
      - parallel:
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.4.3
        - step:
            name: Lint
            script:
              - npm install
              - npm run lint
        - step:
            name: Test
            script: 
              - npm install
              - npm run test-headless
  branches:
    main:
      - step:
          name: Build   
          script: 
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Compress
          script:
            - git fetch origin main:refs/remotes/origin/main
            - git archive --format=tar.gz main -o app-$BITBUCKET_BUILD_NUMBER.tar.gz
          artifacts:
            - "*.zip"
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: app-$BITBUCKET_BUILD_NUMBER.tar.gz